Document: mkchromecast
Title: Debian mkchromecast Manual
Author: <insert document author here>
Abstract: This manual describes what mkchromecast is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mkchromecast/mkchromecast.sgml.gz

Format: postscript
Files: /usr/share/doc/mkchromecast/mkchromecast.ps.gz

Format: text
Files: /usr/share/doc/mkchromecast/mkchromecast.text.gz

Format: HTML
Index: /usr/share/doc/mkchromecast/html/index.html
Files: /usr/share/doc/mkchromecast/html/*.html
